### ISSUE TITLE
[Bug]Found newer version of ArctiumLauncher, cause exception.

### ISSUE THREAD

**Issue by soimy** [0blu/WinterspringLauncher#32] opened 2023-07-14 04:44 UTC
```
Found newer version of ArctiumLauncher, upgrading from latest|Launcher Signed (2022/11/18) => latest|Launcher Signed (2023-07-10)
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at WinterspringLauncher.Launcher.ExecuteGithubDownloadIfUpdateAvailable(String description, String modulePath, GitHubReleaseInfo ghReleaseInfo, Func`2 assetSelector, Action`2 downloader) in D:\a\WinterspringLauncher\WinterspringLauncher\WinterspringLauncher\Program.cs:line 168
   at WinterspringLauncher.Launcher.PrepareArctiumLauncher(UpdateApiClient api, Boolean weAreOnMacOs, String arctiumPath) in D:\a\WinterspringLauncher\WinterspringLauncher\WinterspringLauncher\Program.cs:line 147
   at WinterspringLauncher.Launcher.<>c__DisplayClass2_0.<Main>b__5() in D:\a\WinterspringLauncher\WinterspringLauncher\WinterspringLauncher\Program.cs:line 70
   at WinterspringLauncher.Launcher.IgnoreExceptions(String description, Action func) in D:\a\WinterspringLauncher\WinterspringLauncher\WinterspringLauncher\Program.cs:line 115
>>> Failed to prepare ArctiumLauncher, continuing anyways <<<
```
When launching Wintersprint launcher, exception reported on cosole. But wow client can run & function normally.

**Comment by jactyao** [comment] 2023-07-18 02:27
I hope for an early update for the Mac client. Thank you, thank you.

**Comment by 0blu** [comment] 2023-08-13 11:52
I am increadly sorry for not answering the issue.
I moved and had no real internet access.
I hope the issue is now fixed in the [latest release](https://github.com/0blu/WinterspringLauncher/releases).

**Closed by 0blu** 2023-08-13 11:52 UTC
